# Generated by Django 5.0.4 on 2024-04-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_schedule_visit_schedule_delete_doctorschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='patient',
        ),
    ]
